### ISSUE TITLE
Error [SSL: no alternative certificate subject name matches target host name 'www.remixinstitute.com']

### ISSUE THREAD

**Issue by DimitriF** [AdrianAntico/RemixAutoML#18]
Hello, 
Just had this error with the AutoTS function, it was working yesterday. I could fix it by commenting the image_read of the logo this way lines 3614 of the AutoTS.R file and rebuilding the package.
```
  # logo = magick::image_read(
  #   "https://www.remixinstitute.com/wp-content/uploads/7b-Cheetah_Charcoal_Inline_No_Sub_No_BG.png"
  # )
```

**Comment by DougVegas** [comment]
Yes, you could comment out that section as it just adds the RemixAutoML logo to the plot. It's not necessary for AutoTS to run however. 

The reason why it was error-ing out was because RemixInstitute.com was down on Sunday 6/30/19 and half of Monday 7/1/19. If you run that section now, it will work since RemixInstitute.com is up.
