### ISSUE TITLE
Error in read.dcf(path) :    Found continuation line starting '    c(person(given = ...' at begin of record.

### ISSUE THREAD

**Issue by djhernanv** [AdrianAntico/RemixAutoML#19]
**Error**
The command 
``devtools::install_github('AdrianAntico/RemixAutoML', upgrade = FALSE, dependencies = FALSE, force = TRUE)`` 
throws the error:
``Error in read.dcf(path) : 
  Found continuation line starting '    c(person(given = ...' at begin of record.``

**Similar Issues**
I think that it might be due to an issue with the description files as it was the case in [here](https://github.com/r-lib/devtools/issues/1900).

**Sys Info:** 
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

devtools 2.0.2

----
Thank you!

**Comment by AdrianAntico** [comment]
That has happened to me before. You might need to just restart your computer

**Comment by AdrianAntico** [comment]
Also could be a new dependency to the Matrix package I recently added. It wasn't in the DESCRIPTION file but I just added it.

**Comment by eafpres** [comment]
I'm having the same behavior on an RStudio instance on a Windows VM.

**Comment by AdrianAntico** [comment]
I was able to install from github just now. The only time I had this issue I restarted my computer and it worked fine afterwards. I'm not sure what the underlying cause is, however. As @djhernanv referenced, [Link to broader issue](https://github.com/r-lib/devtools/issues/1900). I see a lot of focus on the DESCRIPTION file but that can't be true, otherwise I would be getting the same error. Have you tried to download another github package to see if you get the same error?

**Comment by eafpres** [comment]
OK, so in the broader issue, there is this:
Digging into this, I found this problem has been fixed here in the remotes package. Until that makes it into CRAN, you can update remotes to the right point using

devtools::install_github("r-lib/remotes", ref = "e56a41e1d0cad55cbe7d60b274b99ab7b7a76b5c")
so I ran:

remotes::install_github('AdrianAntico/RemixAutoML', upgrade = FALSE, dependencies = FALSE, force = TRUE) 

and it starts fine, then fails on magick dependency:

ERROR: dependency 'magick' is not available for package 'RemixAutoML'
* removing 'C:/Program Files/R/R-3.5.3/library/RemixAutoML'
In R CMD INSTALL
Error: Failed to install 'RemixAutoML' from GitHub:
  (converted from warning) installation of package ‘C:/Users/eafpres/AppData/Local/Temp/2/RtmpUbmez9/file2ac40972f26/RemixAutoML_0.5.0.tar.gz’ had non-zero exit status

So i did install.packages('magick') then repeated:

remotes::install_github('AdrianAntico/RemixAutoML', upgrade = FALSE, dependencies = FALSE, force = TRUE) 

and it worked

So, install remotes, install magick, then use remotes instead of devtools

**Comment by AdrianAntico** [comment]
I see the "magick" package wasn't listed in the install script. I just updated that. Do the remote folks have an explanation as to why devtools works on some but not on all?

**Comment by eafpres** [comment]
I'm unsure on the devtools vs. remotes issue; the post said "it was fixed in remotes", which implies there is something wrong in devtools.  That's over my head :-).  

There were also several instances where "fixing" indent "fixed" it but that may be random?

**Comment by AdrianAntico** [comment]
Really odd. I'll make a note in the install script portion of the README to reference this issue if the user is having trouble with installing the package using devtools. Thanks for you help on this!

**Comment by eafpres** [comment]
Thank you for the instant response!  I just found your package and website last night.  Great stuff!

**Comment by djhernanv** [comment]
Hi @AdrianAntico and @eafpres!
Thank you very much for your quick answer! I finally brought it to work. Let me tell you the steps to better understand the underlying issue:

1. I just tried reinstalling to see if the updates in the documentation worked. It didn't install.
2. I updated remotes and magick and tried again. It didn't work.
3. I restarted the R session. It didn't work.
4. I restarded Rstudio. It worked!

May be it is an issue with R Studio? Would be interesting to see if the installation would work from the R GUI for instance.

Anyways, thank you very much!

**Comment by AdrianAntico** [comment]
@djhernanv Thanks for your response. I've had some issues with RStudio, mostly with creating and opening Projects. I'm still able to install the package with devtools so not sure if my results mean anything, but I just checked out installing on the regular R GUI and it worked fine, with devtools. Great suggestion!
