### ISSUE TITLE
Microsoft R Open: Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  :    cannot open URL 

### ISSUE THREAD

**Issue by lejarx** [AdrianAntico/RemixAutoML#37]
`Downloading GitHub repo AdrianAntico/RemixAutoML@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/AdrianAntico/RemixAutoML/tarball/master'`

I want to try Microsoft R Open (MRAN) as alternative to speed up R. Although I face this installation issue when I try to use Microsoft R.

Is this a known issue with MRAN?

**Comment by AdrianAntico** [comment]
@lejarx I haven't tried using RemixAutoML on MRAN. The error message isn't really helpful either. Were you able to download all the dependency packages?

**Comment by lejarx** [comment]
@AdrianAntico Yes, the other dependencies packages are ok except for catboost. It seems I can't install anything from custom location like Github. 

For example, if I try to install the latest tidyverse from Github, it gives the same error
```
devtools::install_github("hadley/tidyverse")
Downloading GitHub repo hadley/tidyverse@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/hadley/tidyverse/tarball/master' 
```

Assumming I'm still using CRAN (instead of MRAN), is there any tips to make the AutoTS() run faster?

**Comment by AdrianAntico** [comment]
@lejarx if you're running it across groups, you could parallelize it so that you are building multiple series at the same time. Note that for several of the internal AutoTS functions, there is a num.core option for parallel building which gets utilized if you set StepWise to FALSE, but this actually increases run times as more models are built while looking for a winner. In general, MRAN won't be helpful at speeding up 95% of the package functions as most computations are either using parallelized C code (openMP via data.table) or parallelized model building functions (CatBoost, H2O, XGBoost).

**Comment by lejarx** [comment]
@AdrianAntico thanks for your insightful answers. I settle with parallelizing across groups for now.

Yes, I also notice that setting StepWise into False, makes the run times much longer, especially when I'm including ARIMA as part of the models, as you mentioned.

Noted on the MRAN as well.
