### ISSUE TITLE
AutoCatBoostCARMA Error

### ISSUE THREAD

**Issue by DrRoad** [AdrianAntico/RemixAutoML#49]
Error in data.table::rbindlist(list(UpdateData[ID != 1], Temporary), use.names = TRUE) : 
  Item 2 has 62 columns, inconsistent with item 1 which has 63 columns. To fill missing columns use fill=TRUE.

**Comment by AdrianAntico** [comment]
@DrRoad Thanks for bringing this up. I have a new release coming soon with upgrades to all the CARMA functions. I'm skipping out on fixing the current versions (there's an issue with the xgboost version as well) because they are so far behind it just doesn't make sense at this point to fix. I'm working on the QA for those upgrades currently. It takes a few weeks to run through all the test cases and make the necessary fixes so please hold tight.

**Comment by DrRoad** [comment]
Thank you. I have also met the similar issue in AutoH2oDRFCARMA and other time series ML functions. Look forward to your new release.

**Comment by AdrianAntico** [comment]
@DrRoad I usually don't make this many upgrades before releasing to the package but this set of upgrades kind of required me to finish all of them before releasing so thank you for your patience. I hope you like the new versions when they come out. Also, I do have more plans to keep enhancing them over time but some of the changes will be pretty tricky so I'll get to them on subsequent releases.

**Comment by DrRoad** [comment]
That's great. I am R developer and I am happy to get involved if there is anything I can help.

**Comment by AdrianAntico** [comment]
Thanks @DrRoad 

Shoot me an email at adrianantico@gmail.com - I'd love to get more people involved! There's so much more to add / enhance to the package. I have a road map for 2020 on the areas I'd like to get to. I'm happy to share that with you and get any ideas you may have :)

**Comment by AdrianAntico** [comment]
@DrRoad release 0.2.0 has AutoCatBoostCARMA() working with many new features. The H2O and XGBoost versions are close behind. Just need to pass all the tests.
