### ISSUE TITLE
Hurdle models - add a scoring function for these models

### ISSUE THREAD

**Issue by Akai01** [AdrianAntico/RemixAutoML#57]
@AdrianAntico  

How do you predict after one of the hurdle model is trained?
Could you give an example how can it be used please?

BR

Res

**Comment by AdrianAntico** [comment]
@Akai01 Hi there. Currently, if you specify SaveModelObjects = TRUE in the function setup then those models will be saved to file and you can use them for scoring. HOWEVER, I haven't set up a scoring function dedicated to these models, mostly because I haven't used them for that purpose as of yet and no one has asked.

**Comment by AdrianAntico** [comment]
@Akai01 I'll make this into a enhancement request issue.

**Comment by AdrianAntico** [comment]
@Akai01 There is now a scoring function available called AutoHurdleScoring(). It's currently only available for the AutoCatBoostHurdleModel() function. I'll be tackling the XGBoost version next. I spent some time on the H2O version but I'm running into some trouble with persisting the H2O instance. Will keep looking into that once I finalize the XGBoost version.
