### ISSUE TITLE
Some items of .SDcols are not column names

### ISSUE THREAD

**Issue by mileta1976** [AdrianAntico/RemixAutoML#65]
I have tried to run example:

https://www.remixinstitute.com/blog/why-machine-learning-is-more-practical-than-time-series-in-the-real-world/#.XwnPb9akpPY

For: AutoH2oDRFCARMA(), AutoH2oGBMCARMA(), AutoXGBoostCARMA()
there is error:

Error in `[.data.table`(data, , `:=`(GroupVar, do.call(paste, c(.SD, sep = " "))),  : 
  Some items of .SDcols are not column names: [Store, Dept]

Thank you !

**Comment by AdrianAntico** [comment]
@mileta1976 I found the glitch and fixed it across the suite of functions. However, there are some new args to the CARMA functions (since that article was written) so you'll want to update the code you attached to reflect those. You can find an example of filling them out in the help files for any of those functions. Be sure to go to the bottom of the help file in the "Examples" section.

**Comment by AdrianAntico** [comment]
Needs a tune up
